%YAML:1.0
# data
vo_type: 'stereo'
# the tum dataset directory, change it to yours! 
dataset_dir: '/work/data/kitti/dataset/sequences/07'
orb_vocab_dir: '/work/proj/ORB_SLAM2/Vocabulary/ORBvoc.txt'
# camera intrinsics, extracted from calib.txt 04, 07
camera.fx:  7.070912000000e+02
camera.fy:  7.070912000000e+02
camera.cx:  6.018873000000e+02
camera.cy:  1.831104000000e+02
# camera intrinsics, extracted from calib.txt 03
#camera.fx:  7.215377000000e+02
#camera.fy:  7.215377000000e+02
#camera.cx:  6.095593000000e+02
#camera.cy:  1.728540000000e+02

camera.base_line: 0.537150

# VO Parameters
number_of_features: 500
scale_factor: 1.2
level_pyramid: 4
match_ratio: 3.0
max_num_lost: 10
min_inliers: 25
keyframe_rotation: 0.05
keyframe_translation: 2.0
map_point_erase_ratio: 0.1
